# Generated by Django 4.2.1 on 2023-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0002_alter_person_initials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingevent",
            name="ring_number",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
