# Generated by Django 4.2.1 on 2023-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0003_alter_samplingevent_ring_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingevent",
            name="ring_number",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
