# Generated by Django 4.2.1 on 2023-07-10 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0005_alter_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="name",
            field=models.CharField(
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[A-Za-z0-9_-]+",
                        "Name must only contain letters, numbers, hyphens, and underscores.",
                    )
                ],
            ),
        ),
    ]
