# Generated by Django 4.2.1 on 2023-08-14 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("repository", "0007_alter_samplingevent_sampling_latitude_dec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingevent",
            name="sampling_latitude_dec",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="samplingevent",
            name="sampling_longitude_dec",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(180),
                    django.core.validators.MinValueValidator(-180),
                ],
            ),
        ),
    ]
