name: test_app
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-22.04 # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: environment.yaml
          environment-name: sampledb-env
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
      - run: flake8 --exclude utils/,repository/migrations/ . # run flake8 test
        shell: micromamba-shell {0}
      - name: "check security"
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_SETTINGS_MODULE: sampledb.settings.production
        run: |
          (python manage.py check --deploy --fail-level ERROR 2>&1 | tee django_check_output.txt ) 
          echo -e "\n--------- Django Security Check results ---------"
          cat django_check_output.txt
          grep "no issues" django_check_output.txt && exit 0 || exit 1
        shell: micromamba-shell {0}
